// Copyright (C) 2026, Cloudflare, Inc.
// All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions are
// met:
//
//     * Redistributions of source code must retain the above copyright notice,
//       this list of conditions and the following disclaimer.
//
//     * Redistributions in binary form must reproduce the above copyright
//       notice, this list of conditions and the following disclaimer in the
//       documentation and/or other materials provided with the distribution.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS
// IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,
// THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
// PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR
// CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
// EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
// PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
// PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
// LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
// NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
// SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

use std::collections::BTreeMap;
use std::collections::VecDeque;
use std::fmt;
use std::net::IpAddr;
use std::net::Ipv4Addr;
use std::sync::Arc;
use std::time::Duration;

use mctx_core::MctxError;
use mctx_core::PublicationConfig;
use mctx_core::SendReport;
use tokio::time::Instant;

use super::bounded_queue::RetainedSize;
use super::event_stream::EventSendError;
use super::event_stream::ManagedEventSender;
use super::runtime::fair_ready_channel_ids;
use super::runtime::validate_server_announce;
use super::server_stream;

/// Bounded batching for integrity generated by
/// [`super::ServerStreamPublisher`].
///
/// This does not alter externally relayed `MC_INTEGRITY` frames. A value of one
/// for `max_packet_hashes` or a zero `max_delay` preserves immediate delivery.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct StreamIntegrityBatchingSettings {
    /// Maximum number of contiguous packet hashes in one `MC_INTEGRITY` frame.
    pub max_packet_hashes: u64,

    /// Maximum time the first packet hash may wait for more contiguous hashes.
    pub max_delay: Duration,
}

impl Default for StreamIntegrityBatchingSettings {
    fn default() -> Self {
        Self {
            max_packet_hashes: 1,
            max_delay: Duration::ZERO,
        }
    }
}

/// Server-side multicast settings for one connection wrapper.
#[derive(Clone, Debug, Default, PartialEq, Eq)]
pub struct ServerControlSettings {
    /// Whether configured control frames should be sent automatically or only
    /// when driven explicitly through
    /// [`ServerControlController`](crate::multicast::ServerControlController).
    pub mode: ServerControlMode,

    /// The multicast channels this server may announce and manage through the
    /// QUIC control connection.
    pub channels: Vec<ServerControlChannelConfig>,

    /// Batching policy for stream-publication integrity frames.
    pub stream_integrity_batching: StreamIntegrityBatchingSettings,
}

/// Automatic or manual sequencing for multicast control frames.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
pub enum ServerControlMode {
    /// Send initial announces and keys automatically, then emit joins when the
    /// peer advertises `MC_LIMITS`.
    #[default]
    Automatic,

    /// Keep channel state locally but only send control frames when the
    /// application explicitly requests them.
    Manual,
}

/// Control-plane configuration for one multicast channel.
#[derive(Clone, PartialEq, Eq)]
pub struct ServerControlChannelConfig {
    /// The announced multicast channel properties.
    pub announce: quiche::multicast::Announce,

    /// The active multicast payload-protection key for the channel.
    pub key: quiche::multicast::Key,
}

impl fmt::Debug for ServerControlChannelConfig {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.debug_struct("ServerControlChannelConfig")
            .field("announce", &self.announce)
            .field("key", &self.key)
            .finish()
    }
}

impl ServerControlChannelConfig {
    pub(super) fn validate(&self) -> quiche::Result<()> {
        validate_server_announce(&self.announce)?;
        self.key.validate()?;

        if self.announce.channel_id != self.key.channel_id {
            return Err(quiche::Error::InvalidState);
        }

        Ok(())
    }
}

impl ServerControlSettings {
    pub(super) fn validate(&self) -> quiche::Result<()> {
        for channel in &self.channels {
            channel.validate()?;
        }

        quiche::multicast::Integrity {
            channel_id: vec![1],
            packet_number_start: 0,
            packet_hash_count: Some(
                self.stream_integrity_batching.max_packet_hashes,
            ),
            packet_hashes: Vec::new(),
        }
        .validate()?;
        Instant::now()
            .checked_add(self.stream_integrity_batching.max_delay)
            .ok_or(quiche::Error::InvalidState)?;

        Ok(())
    }
}

/// Server-side multicast settings for one publication-owning connection
/// wrapper.
#[derive(Clone, Debug, Default, PartialEq, Eq)]
pub struct ServerSettings {
    /// The multicast channels this server may announce and publish.
    pub channels: Vec<ServerChannelConfig>,
}

/// Configuration for one multicast channel served by
/// [`ServerDriver`](crate::multicast::ServerDriver).
#[derive(Clone, PartialEq, Eq)]
pub struct ServerChannelConfig {
    /// The multicast channel ID carried in the draft control frames.
    pub channel_id: Vec<u8>,

    /// The multicast sender socket configuration used by `mctx-core`.
    pub publication: PublicationConfig,

    /// The header protection algorithm from the TLS cipher suite registry.
    pub header_protection_algorithm: u16,

    /// The secret used for multicast short-header protection.
    pub header_secret: Vec<u8>,

    /// The AEAD algorithm from the TLS cipher suite registry.
    pub aead_algorithm: u16,

    /// The packet integrity hash algorithm.
    pub integrity_hash_algorithm: u16,

    /// The maximum multicast payload rate for the channel, in Kibps.
    pub max_rate_kibps: u64,

    /// The maximum delay before sending `MC_ACK`, in milliseconds.
    pub max_ack_delay_ms: u64,

    /// The key sequence number announced to receivers.
    pub key_sequence: u64,

    /// The first packet number protected by `secret`.
    pub from_packet_number: u64,

    /// The multicast payload protection secret.
    pub secret: Vec<u8>,
}

impl fmt::Debug for ServerChannelConfig {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.debug_struct("ServerChannelConfig")
            .field("channel_id", &self.channel_id)
            .field("publication", &self.publication)
            .field(
                "header_protection_algorithm",
                &self.header_protection_algorithm,
            )
            .field(
                "header_secret",
                &format_args!("<redacted:{} bytes>", self.header_secret.len()),
            )
            .field("aead_algorithm", &self.aead_algorithm)
            .field("integrity_hash_algorithm", &self.integrity_hash_algorithm)
            .field("max_rate_kibps", &self.max_rate_kibps)
            .field("max_ack_delay_ms", &self.max_ack_delay_ms)
            .field("key_sequence", &self.key_sequence)
            .field("from_packet_number", &self.from_packet_number)
            .field(
                "secret",
                &format_args!("<redacted:{} bytes>", self.secret.len()),
            )
            .finish()
    }
}

impl Drop for ServerChannelConfig {
    fn drop(&mut self) {
        self.header_secret.fill(0);
        self.secret.fill(0);
    }
}

impl ServerChannelConfig {
    pub(super) fn validate(&self) -> quiche::Result<()> {
        let source = match self.publication.group {
            IpAddr::V4(_) => IpAddr::V4(Ipv4Addr::UNSPECIFIED),
            IpAddr::V6(_) => IpAddr::V6(std::net::Ipv6Addr::UNSPECIFIED),
        };
        let announce = quiche::multicast::Announce {
            channel_id: self.channel_id.clone(),
            source,
            group: self.publication.group,
            udp_port: self.publication.dst_port,
            header_protection_algorithm: self.header_protection_algorithm,
            header_secret: self.header_secret.clone(),
            aead_algorithm: self.aead_algorithm,
            integrity_hash_algorithm: self.integrity_hash_algorithm,
            max_rate_kibps: self.max_rate_kibps,
            max_ack_delay_ms: self.max_ack_delay_ms,
        };
        validate_server_announce(&announce)?;
        self.key_frame().validate()
    }

    pub(super) fn control_channel_from(
        &self, source: Ipv4Addr, group: Ipv4Addr, udp_port: u16,
    ) -> Result<ServerControlChannelConfig, MctxError> {
        Ok(ServerControlChannelConfig {
            announce: self.announce_from(source, group, udp_port)?,
            key: self.key_frame(),
        })
    }

    pub(super) fn announce_from(
        &self, source: Ipv4Addr, group: Ipv4Addr, udp_port: u16,
    ) -> Result<quiche::multicast::Announce, MctxError> {
        Ok(quiche::multicast::Announce {
            channel_id: self.channel_id.clone(),
            source: IpAddr::V4(source),
            group: IpAddr::V4(group),
            udp_port,
            header_protection_algorithm: self.header_protection_algorithm,
            header_secret: self.header_secret.clone(),
            aead_algorithm: self.aead_algorithm,
            integrity_hash_algorithm: self.integrity_hash_algorithm,
            max_rate_kibps: self.max_rate_kibps,
            max_ack_delay_ms: self.max_ack_delay_ms,
        })
    }

    pub(super) fn key_frame(&self) -> quiche::multicast::Key {
        quiche::multicast::Key {
            channel_id: self.channel_id.clone(),
            key_sequence: self.key_sequence,
            from_packet_number: self.from_packet_number,
            secret: self.secret.clone(),
        }
    }
}

impl ServerSettings {
    pub(super) fn validate(&self) -> quiche::Result<()> {
        for channel in &self.channels {
            channel.validate()?;
        }

        Ok(())
    }
}

/// Events emitted by [`ServerDriver`](crate::multicast::ServerDriver).
#[derive(Debug)]
pub enum ServerEvent {
    /// The client advertised updated multicast limits.
    ClientLimits(quiche::multicast::Limits),

    /// The client reported multicast channel state.
    ClientState(quiche::multicast::State),

    /// The client acknowledged multicast packet ranges.
    ClientAck(quiche::multicast::Ack),

    /// The connection-local multicast path changed viability state.
    ///
    /// This includes probing, successful ACK validation, ACK-freshness
    /// timeout, join failure, leave, and retirement transitions.
    ProbeStatusChanged(quiche::multicast::ProbeEvent),

    /// A multicast packet was successfully published on a channel.
    Published {
        /// The QUIC multicast channel ID associated with the packet.
        channel_id: Vec<u8>,

        /// The multicast channel packet number carried on the wire.
        packet_number: u64,

        /// The send report returned by `mctx-core`.
        report: SendReport,
    },

    /// The server could not encode a multicast packet command.
    EncodeError {
        /// The QUIC multicast channel ID associated with the failed command.
        channel_id: Vec<u8>,

        /// The core multicast encoding error reported by `quiche`.
        error: quiche::Error,
    },

    /// The server could not publish an encoded multicast packet.
    PublishError {
        /// The QUIC multicast channel ID associated with the failed publish.
        channel_id: Vec<u8>,

        /// The underlying multicast sender error from `mctx-core`.
        error: MctxError,
    },
}

pub(super) enum PendingClientAckAction {
    Ack(quiche::multicast::Ack),
    Reset,
}

#[derive(Default)]
pub(super) struct ServerEventCoalescer {
    pub(super) pending_client_acks:
        BTreeMap<Vec<u8>, VecDeque<PendingClientAckAction>>,
    pub(super) last_client_acks: BTreeMap<Vec<u8>, quiche::multicast::Ack>,
    pub(super) last_probe_events:
        BTreeMap<Vec<u8>, quiche::multicast::ProbeEvent>,
    pub(super) ack_flush_cursor: Option<Vec<u8>>,
}

impl ServerEventCoalescer {
    pub(super) fn has_pending_client_acks(&self) -> bool {
        self.pending_client_acks
            .values()
            .any(|pending| !pending.is_empty())
    }

    pub(super) fn queue_client_ack(
        &mut self, event_sender: &ManagedEventSender<ServerEvent>,
        frame: quiche::multicast::Ack,
    ) {
        let pending = self
            .pending_client_acks
            .entry(frame.channel_id.clone())
            .or_default();
        let matches_pending = pending.back().is_some_and(|previous| {
            matches!(
                previous,
                PendingClientAckAction::Ack(previous) if previous == &frame
            )
        });
        let matches_delivered = pending.is_empty() &&
            self.last_client_acks
                .get(&frame.channel_id)
                .is_some_and(|previous| previous == &frame);
        if matches_pending || matches_delivered {
            event_sender.record_identical_coalesced();
            return;
        }
        pending.push_back(PendingClientAckAction::Ack(frame));
    }

    pub(super) fn flush_client_acks(
        &mut self, event_sender: &ManagedEventSender<ServerEvent>,
        max_work: usize,
    ) -> Result<usize, EventSendError> {
        let mut work = 0;
        while work < max_work {
            if !self.flush_one_client_ack(event_sender)? {
                break;
            }
            work += 1;
        }

        Ok(work)
    }

    pub(super) fn flush_one_client_ack(
        &mut self, event_sender: &ManagedEventSender<ServerEvent>,
    ) -> Result<bool, EventSendError> {
        let Some(channel_id) = fair_ready_channel_ids(
            &self.pending_client_acks,
            self.ack_flush_cursor.as_deref(),
            1,
            |pending| !pending.is_empty(),
        )
        .pop() else {
            return Ok(false);
        };
        self.ack_flush_cursor = Some(channel_id.clone());
        let action = self
            .pending_client_acks
            .get_mut(&channel_id)
            .and_then(VecDeque::pop_front)
            .expect("selected channel has pending ACK work");
        if self
            .pending_client_acks
            .get(&channel_id)
            .is_some_and(VecDeque::is_empty)
        {
            self.pending_client_acks.remove(&channel_id);
        }

        match action {
            PendingClientAckAction::Ack(frame) => {
                self.last_client_acks.insert(channel_id, frame.clone());
                event_sender.try_send(ServerEvent::ClientAck(frame))?;
            },

            PendingClientAckAction::Reset => {
                self.last_client_acks.remove(&channel_id);
            },
        }

        Ok(true)
    }

    pub(super) fn reset_channel(&mut self, channel_id: &[u8]) {
        let pending = self
            .pending_client_acks
            .entry(channel_id.to_vec())
            .or_default();
        if !matches!(pending.back(), Some(PendingClientAckAction::Reset)) {
            pending.push_back(PendingClientAckAction::Reset);
        }
        self.last_client_acks.remove(channel_id);
        self.last_probe_events.remove(channel_id);
    }

    pub(super) fn forward_probe_event(
        &mut self, event_sender: &ManagedEventSender<ServerEvent>,
        event: quiche::multicast::ProbeEvent,
    ) -> Result<(), EventSendError> {
        if self
            .last_probe_events
            .get(&event.channel_id)
            .is_some_and(|previous| previous == &event)
        {
            event_sender.record_identical_coalesced();
            return Ok(());
        }

        self.last_probe_events
            .insert(event.channel_id.clone(), event.clone());
        event_sender.try_send(ServerEvent::ProbeStatusChanged(event))
    }

    pub(super) fn clear(&mut self) {
        self.pending_client_acks.clear();
        self.last_client_acks.clear();
        self.last_probe_events.clear();
        self.ack_flush_cursor = None;
    }
}

#[derive(Debug, thiserror::Error)]
pub(super) enum ServerError {
    #[error("multicast server wrapper only supports server connections")]
    ClientConnectionUnsupported,

    #[error("multicast publication failed: {0}")]
    Publication(#[from] MctxError),

    #[error("{0} multicast runtime queue exhausted")]
    RuntimeQueueExhausted(&'static str),

    #[error("multicast control queue made no progress for {0:?}")]
    ControlBackpressureTimeout(Duration),

    #[error(
        "multicast runtime exhausted its connection-lifetime Channel ID limit of {0}"
    )]
    TrackedChannelIdLimit(usize),
}

impl RetainedSize for quiche::multicast::Integrity {
    fn retained_size(&self) -> usize {
        integrity_retained_size(self)
    }
}

impl RetainedSize for Arc<server_stream::CommittedServerStreamPublication> {
    fn retained_size(&self) -> usize {
        self.frame
            .data
            .len()
            .saturating_add(integrity_retained_size(&self.integrity))
            .saturating_add(128)
    }
}

pub(super) fn announce_retained_size(
    frame: &quiche::multicast::Announce,
) -> usize {
    frame
        .channel_id
        .len()
        .saturating_add(frame.header_secret.len())
        .saturating_add(128)
}

pub(super) fn key_retained_size(frame: &quiche::multicast::Key) -> usize {
    frame
        .channel_id
        .len()
        .saturating_add(frame.secret.len())
        .saturating_add(96)
}

pub(super) fn integrity_retained_size(
    frame: &quiche::multicast::Integrity,
) -> usize {
    frame
        .channel_id
        .len()
        .saturating_add(frame.packet_hashes.len())
        .saturating_add(96)
}

pub(super) fn control_config_retained_size(
    config: &ServerControlChannelConfig,
) -> usize {
    announce_retained_size(&config.announce)
        .saturating_add(key_retained_size(&config.key))
}
